# CoffeeMek Production Simulator Configuration

# Kafka Configuration
kafka:
  bootstrap_servers: "165.227.168.240:29093"
  topics:
    input: "mokametrics.order"
    telemetry_prefix: "mokametrics.telemetry"
    production_completion: "mokametrics.production.lot_completion"

# API Configuration
api:
  endpoint_url: "https://mokametrics-api-fafshjgtf4degege.italynorth-01.azurewebsites.net"
  api_key: "" # Set via MOKAMETRICS_API_KEY environment variable
  enable_api: false # Set via ENABLE_API environment variable

# Health Check Configuration
health_check:
  port: 8084

# Factory Configuration
factory:
  location_codes:
    Italy: "IT"
    Brazil: "BR"
    Vietnam: "VN"

# Machine Configuration by Location
# Exactly 1 machine per type per location = 12 total machines
machines:
  Italy:
    cnc: 1
    lathe: 1
    assembly_line: 1
    test_line: 1
  Brazil:
    cnc: 1
    lathe: 1
    assembly_line: 1
    test_line: 1
  Vietnam:
    cnc: 1
    lathe: 1
    assembly_line: 1
    test_line: 1

# Processing Time Configuration (in seconds)
processing_times:
  cnc:
    min: 1200 # 20 minutes
    max: 3600 # 60 minutes
  lathe:
    min: 900 # 15 minutes
    max: 2700 # 45 minutes
  assembly:
    min: 1800 # 30 minutes
    max: 5400 # 90 minutes
  test:
    min: 600 # 10 minutes
    max: 1800 # 30 minutes

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Simulation Parameters
simulation:
  status_report_interval: 60 # seconds
  machine_block_probability: 0.05 # 5% chance of machine blocking
  priority_processing: true # Process high priority lots first
