version: '3.8'

services:
  mokametrics-simulator:
    build: .
    container_name: mokametrics-simulator
    restart: unless-stopped
    ports:
      - "8083:8083"  # Health check port
    environment:
      # Kafka Configuration
      - KAFKA_BROKER=165.227.168.240:29093
      
      # API Configuration (optional)
      - MOKAMETRICS_API_KEY=${MOKAMETRICS_API_KEY:-}
      - ENABLE_API=${ENABLE_API:-false}
      
      # Health Check Configuration
      - HEALTH_CHECK_PORT=8083
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
    volumes:
      # Mount config file for easy updates
      - ./config.yaml:/app/config.yaml:ro
      
      # Optional: Mount logs directory
      - ./logs:/app/logs
      
    networks:
      - mokametrics-network
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mokametrics-network:
    driver: bridge
